apiVersion: v1
kind: Template
metadata:
  name: ansible-executor
labels:
  template: ansible-executor

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "ansible-executor"
    annotations:
      description: "A container used to execute ansible commands"
      openshift.io/display-name: "Ansible Executor (Ephemeral)"
      iconClass: ansible
      tags: "ansible"
      openshift.io/provider-display-name: "Red Hat, Inc."
  spec: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "ansible-executor"
  spec:
    triggers:
    - type: ConfigChange
    source:
      type: DockerFile
      dockerfile: "FROM contrainfra/ansible-executor:v1.1.2"
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: ansible-executor
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
        noCache: true
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: ansible-executor:latest
