apiVersion: v1
kind: Template
metadata:
  name: ansible-executor
labels:
  template: ansible-executor

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "ansible-executor"
    annotations:
      description: "A container used to execute ansible commands"
      openshift.io/display-name: "Anisble Executor (Ephermal)"
      iconClass: ansible
      tags: "ansible"
      openshift.io/provider-display-name: "Red Hat, Inc."
  spec: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "ansible-executor"
  spec:
    triggers:
    - type: ConfigChange
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: ansible-executor
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: ansible-executor:latest
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repostory URL
  name: REPO_URL
  value: https://gitlab.sat.lab.tlv.redhat.com/contra/hdsl.git
- description: The subdirectory inside the repo, containing the Dockerfile
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/dockerfiles/ansible
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: development
